variables:
   GIT_CLEAN_FLAGS: none

stages:
   - pre_build
   - environment_setup
   - quality_gate
   - deploy

install_dependencies:
   stage: pre_build
   cache:
      key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
      paths:
         - node_modules/
   script:
      - npm ci
   only:
      refs:
         - staging
      changes:
         - package-lock.json

env_setup:
   stage: environment_setup
   script:
      - "rm .env || :"
      - echo REACT_APP_BASE_URL = https://sky-launch-main.skylaunch.online >> .env
   only:
      - staging

scanning:
   stage: quality_gate
   allow_failure: true
   script:
      - sonar-scanner
   only:
      - staging

deploy:
   stage: deploy
   cache:
      key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
      paths:
         - node_modules/
      policy: pull
   script:
      - npm run build
   environment:
      name: staging
   only:
      - staging
